name: 'Docker Build/Push'
description: 'Builds a Docker image and pushes it to a registry'

inputs:
  push:
    description: 'Whether to push the image to the registry'
    type: boolean
    required: true
    default: true
  image_name:
    description: 'Name of the Docker image'
    required: true
  registry:
    description: 'Docker registry URL'
    required: true
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password or token'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
  context:
    description: 'Build context'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Log in to Docker registry
      shell: bash
      run: echo "${{ inputs.password }}" | docker login ${{ inputs.registry }} -u ${{ inputs.username }} --password-stdin

    - name: Build Docker image
      shell: bash
      run: docker build -f ${{ inputs.dockerfile }} -t ${{ inputs.registry }}/${{ inputs.image_name }} ${{ inputs.context }}

    - name: Push Docker image
      shell: bash
      run: docker push ${{ inputs.registry }}/${{ inputs.image_name }}